### PR TITLE
CSharp coding standard: Reorder access modifiers #58

### LINKED ISSUE #58: CSharp coding standard: Reorder access modifiers
The current order for access modifiers in the standard is `public, protected, internal, private`.

However, StyleCop can only analyse based on this order: `public, internal, protected internal, protected, private`.

Not only that, it makes sense for internal to go before protected, as internal has a larger scope (all files in the same assembly), as opposed to protected (containing class and derivations of that class). Thus, the access modifier will be ordered based on visibility.

### PR DESCRIPTION
**Pull request by Skaty**
Fixes #58
[Preview](https://github.com/Skaty/process/blob/58-csharp-access-modifiers/codingStandards/CodingStandard-CSharp.md)

### CODE REVIEW

**Comment by damithc** [comment]
@AngShiYa can peer review?

**Comment by PierceAndy** [comment]
As a side note, the preview link is not necessary.

Under each commit, you can view the rich diff here 
image

And you can preview the whole changed file here 
image

**Comment by Skaty** [comment]
@AngShiYa Since `protected internal` means protected OR internal, it should be less stronger than an actual `internal`, due to its specificity.

**Comment by AngShiYa** [comment]
@Skaty But shouldn't `protected internal` be less specific because it accepts either `protected` and `internal`?

**Comment by acjh** [comment]
In terms of visibility, `internal` ≥ `protected internal` ≥ `protected`.

In fact, the specificity would be **equal** if we consider the CSS analogy:
```css
internal {
    /* styles */
}

protected, internal {
    /* common styles */
}

protected {
    /* styles */
}
```

**Comment by Skaty** [comment]
@AngShiYa I meant `internal` is more specific than `protected internal`.

@acjh That kinda adds up to the ordering in some way if you based it on visibility.

**Comment by yamgent** [comment]
Noticed that you referred to StyleCop in the other PR for the ordering rules. I suggest that you mention that the ordering rules came from StyleCop. Conforming with standards followed by StyleCop could be a stronger justification than simply stating that it is ordered by visibility, because there can be disagreement about the visibility order.

With that being said...

> In terms of visibility, `internal` ≥ `protected internal` ≥ `protected`.

I have a different perspective of the visibility, such that `internal` < `protected internal`. Here's my justification:

accessibility

**Comment by acjh** [comment]
I stand corrected.

I realized my CSS analogy already shows bigger scope/visibility for `protected internal`,
i.e. `internal` is more *restrictive* than `protected internal`.

Concrete example in C# that you can paste into [repl.it](https://repl.it/languages/csharp):
```c#
public class _ {
  internal class one {

  }

  protected internal class two: one {

  }
}
```
```
main.cs(6,28): error CS0060: Inconsistent accessibility: base class `_.one' is less accessible than class `_.two'
main.cs(2,18): (Location of the symbol related to previous error)
Compilation failed: 1 error(s), 0 warnings

exit status 1
```

**Comment by Skaty** [comment]
Even if we agree on a different ordering, it doesn't help that StyleCop forces `public, internal, protected internal, protected, private`.

**Comment by yamgent** [comment]
@Skaty Yes, which is the reason why I suggested that you mention StyleCop in the coding standards.

**Comment by AngShiYa** [comment]
@Skaty But at least this argument will not be wasted if you can add in how a different ordering was discussed but we decided to follow StyleCop for the ease of standardization ;)

**Comment by damithc** [comment]
@Skaty what's the status of this PR?

**Comment by Skaty** [comment]
@damithc, I don't know, because they stopped arguing.

**Comment by yamgent** [comment]
@Skaty the argument stopped because there is nothing left to discuss. A flaw was pointed out and @acjh kindly corrected his stand. I apologies if our discussion was confusing or unclear.

You are correct that the argument is not productive. That was the basis of my original recommendation, in which any further arguments can simply be avoided by putting a stronger justification, which is to mention StyleCop in the coding standards:

> I suggest that you mention that the ordering rules came from StyleCop. Conforming with standards followed by StyleCop could be a stronger justification than simply stating that it is ordered by visibility, because there can be disagreement about the visibility order.

You are welcome to agree or disagree with the recommendation. :-)

**Comment by damithc** [comment]
@AngShiYa your decision (approve/request change)
@Skaty please request reviews from another peer.

**Comment by Skaty** [comment]
@acjh @AngShiYa @yamgent @damithc 
Added indication that ordering is based on StyleCop.

**Comment by Skaty** [comment]
@AngShiYa It's not a good idea to put a PR link in a standards document that may last longer than this repository being in GitHub. The comment is sufficient enough.

**Pull request merged**
